import { TbReport, TbFileInvoice } from "react-icons/tb";
import { CiSettings } from "react-icons/ci";

export const listMenu = [
  {
    id: 1,
    link: "dashboard/transaksi",
    name: "Laporan Transaksi",
    icon: <TbReport size={25} />,
    active: true,
    subMenu: [
      {
        id: 2,
        link: "dashboard/laporan/penjualan",
        name: "Penjualan",
        icon: null,
        active: true,
        subMenu: [],
      },
      {
        id: 3,
        link: "dashboard/laporan/pembelian",
        name: "Pembelian",
        icon: null,
        active: true,
        subMenu: [],
      },
    ],
  },
  {
    id: 4,
    link: "dashboard/transaksi/pembelian",
    name: "Pembelian",
    icon: <TbFileInvoice size={25} />,
    active: true,
    subMenu: [],
  },
  {
    id: 5,
    link: "dashboard/transaksi/penjualan",
    name: "Penjualan",
    icon: <TbFileInvoice size={25} />,
    active: true,
    subMenu: [],
  },
  {
    id: 9,
    link: "dashboard/member",
    name: "Member Info",
    icon: <TbFileInvoice size={25} />,
    active: true,
    subMenu: [],
  },
  {
    id: 6,
    link: "dashboard/setting",
    name: "User Konfigurasi",
    icon: <CiSettings size={25} />,
    active: true,
    subMenu: [
      {
        id: 9,
        link: "dashboard/setting/passwordchange",
        name: "User Maintenance",
        icon: null,
        active: true,
        subMenu: [],
      },
      {
        id: 10,
        link: "dashboard/setting/passwordchange",
        name: "User Group Maintenance",
        icon: null,
        active: true,
        subMenu: [],
      },
      {
        id: 7,
        link: "dashboard/setting/passwordchange",
        name: "Ganti Password",
        icon: null,
        active: true,
        subMenu: [],
      },
      {
        id: 8,
        link: "dashboard/setting/pembelian",
        name: "Ganti Username",
        icon: null,
        active: true,
        subMenu: [],
      },
    ],
  },
];
